---
name: top
description: A new Flutter project.
publish_to: none
version: 1.0.1+0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  animate_do: ^3.3.4
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  path_provider: ^2.1.3
  smooth_page_indicator: ^1.1.0
  stylish_bottom_bar: ^1.1.0
  typewritertext: ^3.0.6
  uuid: ^4.4.0
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.1
  cloud_firestore: ^4.14.0
  provider: ^6.1.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/top-icon.png
flutter:
  uses-material-design: true
  assets:
  - assets/
flutter_native_splash:
  color: '#000000'
  image: assets/top-transparent-icon.png
  android_12:
    image: assets/top-transparent-icon.png
    color: '#000000'
